name: Build

on:
  issue_comment:
    types: [created]

jobs:
  get-context:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
